name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
          fetch-depth: 0
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./main
      - name: Comile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew assemble compileTestJava sonarqube
        working-directory: ./main
      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: 'master'
          workflow_id: 'build.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: get diff
        id: diff
        run: |
          echo "::set-output name=diff::$(git diff --name-only ${{ steps.last_successful_commit.outputs.commit_hash }} | grep '.*.java')"
        working-directory: ./main
      - name: Run Tests
        uses: martinunterhuber/test-runner@master
        with:
          project-root: /home/runner/work/test-project/test-project/main/
          diff: "${{ steps.diff.outputs.diff }}"
